### ISSUE TITLE
FYI: Breakage in chrome canary.

### ISSUE THREAD

**Issue by dsifford** [dracula/chrome-devtools#2]
![image](https://cloud.githubusercontent.com/assets/5240018/15483265/d10920c8-2101-11e6-9d6e-f20e6f534ddb.png)

**Comment by Artistan** [comment]
I just had a similar issue. try going to settings and set chromes setting to "dark"
that helped for me, seems to be their dark vs light theme option changes the layouts and such.

**Comment by R3V07T** [comment]
lol i made that looks tht way  because it was darker my  screen will be
black and i wont get it back to normaL i was testing a new theme im
work8ing on

**Comment by R3V07T** [comment]
Hey i got some way better  stuff than this i had it since 2016 i just dont know how to apply it to ??
