### ISSUE TITLE
The scroll bar on the sources tab is see-through under it

### ISSUE THREAD

**Issue by AskYous** [dracula/chrome-devtools#3]
It's showing the code under the scroll bar.

![image](https://cloud.githubusercontent.com/assets/791996/22271188/25faf748-e248-11e6-82d6-f218d3ea2ee6.png)

**Comment by jacksaunders** [comment]
Hey @AskYous Cant seem to replicate this can you test again and let me know if it is still doing it

**Comment by jacksaunders** [comment]
Fixed in v2.0.3
