### ISSUE TITLE
Adding styles to the page through devtools is unreadable

### ISSUE THREAD

**Issue by benreyn** [dracula/chrome-devtools#4]
When adding a style to a page through devtools the style property is nice and readable when typing, but the value you give to that property cannot be read as you are typing. See screenshot below...

![new_issue_ _dracula_chrome-devtools](https://cloud.githubusercontent.com/assets/11561578/22891114/edff2738-f1d3-11e6-8424-ecd332518864.png)

**Comment by jacksaunders** [comment]
@benjamingarcia what version of chrome is this, my version does not seem to have that feature

**Comment by benreyn** [comment]
Version `56.0.2924.87`

I'm pretty sure this has been a feature in chrome for some time. Just inspect an element on a page and click on one of the styles listed to edit it.

**Comment by jacksaunders** [comment]
Fixed in v2.0.3
