### ISSUE TITLE
Inherited styles _kind of_ hard to read

### ISSUE THREAD

**Issue by benreyn** [dracula/chrome-devtools#5]
I think these would be easier to read with a darker background color...

![chrome-devtools_less_at_master_ _dracula_chrome-devtools](https://cloud.githubusercontent.com/assets/11561578/22896980/92cf1b7a-f1e7-11e6-9f28-5207bad4538d.png)

**Comment by zenorocha** [comment]
Hey @jacksaunders, can you take a look?
