### ISSUE TITLE
To bright in computed styles

### ISSUE THREAD

**Issue by Artistan** [dracula/chrome-devtools#7]
Computed Styles is very bright.

![image](https://user-images.githubusercontent.com/801349/33558994-09e1618e-d8d1-11e7-84c6-658f044abf69.png)

**Comment by R3V07T** [comment]
Turn Brightness down 50%or below it will look better  its that bright for a reason -N30

**Comment by Artistan** [comment]
is there I brightness setting? I do not see it. 
![image](https://user-images.githubusercontent.com/801349/33716825-371bdef6-db1d-11e7-89c7-2f46b1c99f46.png)
LOL

**Comment by Artistan** [comment]
theme set to Dark ... was light, but not light??
![image](https://user-images.githubusercontent.com/801349/33716863-64ef379c-db1d-11e7-968c-793c1d635351.png)

Now Computed looks ok...
![image](https://user-images.githubusercontent.com/801349/33716902-7f794e68-db1d-11e7-8a5d-f829fb3c7707.png)

**Comment by Artistan** [comment]
looks like not it is chromes dark theme, not dracula.

**Comment by Artistan** [comment]
Chrome's dark option seems better. thanks for the reponse

**Comment by R3V07T** [comment]
settings in windows brightness is high or change windows theme...i think making desktop backround red would bring it back depending on transparency settings
